env: dev2
server:
  port: 8088
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8762/eureka
spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/pm110?serverTimezone=UTC
  application:
    name: order
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  rabbitmq:
    host: 192.168.0.107
    username: guest
    password: guest
    port: 5672
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
