env: product-dev28
server:
  port: 8089
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8762/eureka
spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pm110
  application:
    name: product
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
